=== samply/nngm-explorer/schema/options.schema.json
{
	"$ref": "#/definitions/Options",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"ChartOption": {
			"additionalProperties": false,
			"properties": {
				"accumulatedValues": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"name": {
								"type": "string"
							},
							"values": {
								"items": {
									"type": "string"
								},
								"type": "array"
							}
						},
						"required": ["name", "values"],
						"type": "object"
					},
					"type": "array"
				},
				"aggregations": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"hintText": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"legendMapping": {
					"additionalProperties": {
						"type": "string"
					},
					"type": "object"
				},
				"tooltips": {
					"additionalProperties": {
						"type": "string"
					},
					"type": "object"
				}
			},
			"type": "object"
		},
		"ChartOptions": {
			"additionalProperties": {
				"$ref": "#/definitions/ChartOption"
			},
			"type": "object"
		},
		"FacetCountOptions": {
			"additionalProperties": false,
			"properties": {
				"hoverText": {
					"additionalProperties": {
						"type": "string"
					},
					"description": "Hover text for each stratifier in the catalogue",
					"type": "object"
				}
			},
			"required": ["hoverText"],
			"type": "object"
		},
		"HeaderData": {
			"additionalProperties": false,
			"properties": {
				"aggregatedDataKeys": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"groupCode": {
								"type": "string"
							},
							"stratifierCode": {
								"type": "string"
							},
							"stratumCode": {
								"type": "string"
							}
						},
						"type": "object"
					},
					"type": "array"
				},
				"dataKey": {
					"type": "string"
				},
				"hintText": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"title": {
					"type": "string"
				}
			},
			"required": ["title"],
			"type": "object"
		},
		"NegotiateOptions": {
			"additionalProperties": false,
			"properties": {
				"authorizationHeader": {
					"description": "The value of the Authorization header for the POST request.",
					"type": "string"
				},
				"siteMappings": {
					"description": "Maps the site names in the results table to the unique identifiers expected by the BBMRI Negotiator.",
					"items": {
						"$ref": "#/definitions/NegotiateOptionsSiteMapping"
					},
					"type": "array"
				},
				"url": {
					"description": "The URL of the BBMRI Negotiator API endpoint that creates a request to apply for access. The URL path is typically /api/v3/requests. Lens will send a POST request to the URL to start the application process.",
					"type": "string"
				}
			},
			"required": ["url", "authorizationHeader", "siteMappings"],
			"type": "object"
		},
		"NegotiateOptionsSiteMapping": {
			"additionalProperties": false,
			"properties": {
				"collection": {
					"description": "Unique identifier of the collection, e.g. \"bbmri-eric:ID:DE_RWTHCBMB:collection:RWTHCBMB_BC\"",
					"type": "string"
				},
				"collection_name": {
					"description": "Name of the collection, e.g. \"Collection of RWTH cBMB Broad Consent Aachen\"",
					"type": "string"
				},
				"site": {
					"description": "Name of the site, e.g. \"Aachen\". This must correspond to the site names as they are displayed in the results table.",
					"type": "string"
				},
				"site_id": {
					"description": "Unique identifier of the site, e.g. \"bbmri-eric:ID:DE_RWTHCBMB\"",
					"type": "string"
				}
			},
			"required": ["site", "collection", "site_id", "collection_name"],
			"type": "object"
		},
		"Options": {
			"additionalProperties": false,
			"properties": {
				"autoUpdateQueryInUrl": {
					"description": "Whether to automatically update the query in the URL when it changes (default: true)",
					"type": "boolean"
				},
				"chartOptions": {
					"$ref": "#/definitions/ChartOptions"
				},
				"facetCount": {
					"$ref": "#/definitions/FacetCountOptions",
					"description": "If set, fetch and display facet counts (number of results per discrete value) in the catalogue."
				},
				"language": {
					"description": "Two letter language code of the application language",
					"type": "string"
				},
				"negotiateOptions": {
					"$ref": "#/definitions/NegotiateOptions"
				},
				"projectmanagerOptions": {
					"$ref": "#/definitions/ProjectManagerOptions"
				},
				"resultSummaryOptions": {
					"$ref": "#/definitions/ResultSummaryOptions"
				},
				"siteMappings": {
					"additionalProperties": {
						"type": "string"
					},
					"type": "object"
				},
				"sitesToQuery": {
					"description": "List of sites to query used by `querySpot` function and facet counts. If not set no sites are sent to Spot and Spot determines the sites to query.",
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"spotUrl": {
					"description": "URL of the Spot API endpoint used by `querySpot` function and facet counts.",
					"type": "string"
				},
				"tableOptions": {
					"$ref": "#/definitions/TableOptions"
				},
				"texts": {
					"$ref": "#/definitions/Texts",
					"description": "Allows to customize texts and add new translations"
				}
			},
			"type": "object"
		},
		"ProjectManagerOptions": {
			"additionalProperties": false,
			"properties": {
				"editProjectUrl": {
					"type": "string"
				},
				"newProjectUrl": {
					"type": "string"
				},
				"siteMappings": {
					"items": {
						"$ref": "#/definitions/ProjectManagerOptionsSiteMapping"
					},
					"type": "array"
				}
			},
			"required": ["newProjectUrl", "editProjectUrl", "siteMappings"],
			"type": "object"
		},
		"ProjectManagerOptionsSiteMapping": {
			"additionalProperties": false,
			"properties": {
				"collection": {
					"type": "string"
				},
				"site": {
					"type": "string"
				}
			},
			"required": ["site", "collection"],
			"type": "object"
		},
		"ResultSummaryOptions": {
			"additionalProperties": false,
			"properties": {
				"dataTypes": {
					"items": {
						"$ref": "#/definitions/HeaderData"
					},
					"type": "array"
				},
				"infoButtonText": {
					"type": "string"
				},
				"title": {
					"type": "string"
				}
			},
			"required": ["dataTypes"],
			"type": "object"
		},
		"TableOptions": {
			"additionalProperties": false,
			"properties": {
				"headerData": {
					"items": {
						"$ref": "#/definitions/HeaderData"
					},
					"type": "array"
				}
			},
			"required": ["headerData"],
			"type": "object"
		},
		"Texts": {
			"additionalProperties": {
				"additionalProperties": {
					"type": "string"
				},
				"type": "object"
			},
			"description": "A map of texts that are displayed in the application. The keys are used to look up the text in the application code. The values are objects that map two letter language codes to the actual text.",
			"type": "object"
		}
	}
}

=== samply/nngm-explorer/src/config/options.json
{
	"siteMappings": {
		"berlin-test": "Berlin",
		"bonn": "Bonn",
		"dresden": "Dresden",
		"essen": "Essen",
		"frankfurt": "Frankfurt",
		"freiburg": "Freiburg",
		"hannover": "Hannover",
		"mainz": "Mainz",
		"muenchen-lmu": "München(LMU)",
		"muenchen-tum": "München(TUM)",
		"ulm": "Ulm",
		"wuerzburg": "Würzburg",
		"mannheim": "Mannheim",
		"dktk-test": "DKTK-Test",
		"hamburg": "Hamburg",
		"nngm-test": "NDP",
		"proxy2": "NDP"
	},
	"chartOptions": {
		"patients": {
			"legendMapping": {
				"berlin": "Berlin",
				"berlin-test": "Berlin",
				"bonn": "Bonn",
				"dresden": "Dresden",
				"essen": "Essen",
				"frankfurt": "Frankfurt",
				"freiburg": "Freiburg",
				"hannover": "Hannover",
				"mainz": "Mainz",
				"muenchen-lmu": "München(LMU)",
				"muenchen-tum": "München(TUM)",
				"ulm": "Ulm",
				"wuerzburg": "Würzburg",
				"mannheim": "Mannheim",
				"dktk-test": "DKTK-Test",
				"hamburg": "Hamburg"
			}
		},
		"gender": {
			"legendMapping": {
				"male": "Männlich",
				"female": "Weiblich",
				"unknown": "Unbekannt",
				"other": "Divers"
			}
		},
		"diagnosis": {
			"hintText": [
				"Bei Patienten mit mehreren onkologischen Diagnosen werden auch Einträge angezeigt, die ggfs. nicht den ausgewählten Suchkriterien entsprechen."
			]
		},
		"age_at_diagnosis": {
			"hintText": [
				"Bei Patienten mit mehreren Erstdiagnosen werden auch Einträge angezeigt, die ggfs. außerhalb der Suchkriterien liegen. "
			]
		},
		"67162-8": {
			"hintText": [
				"\"verstorben\": ein Todesdatum ist dokumentiert oder das aktuelle Lebensalter ist größer 123 Jahre.",
				"\"lebend\": wird angenommen, wenn kein Todesdatum dokumentiert ist oder das aktuelle Lebensalter nicht 123 Jahre überschritten hat.",
				"\"unbekannt\": kein Geburtsdatum oder Todesdatum bekannt."
			],
			"legendMapping": {
				"L": "lebt",
				"T": "verstorben",
				"A": "lost to follow-up"
			}
		},
		"72166-2": {
			"legendMapping": {
				"LA15920-4": "Ehemaliger Raucher",
				"LA18978-9": "Niemals Raucher",
				"LA18979-7": "Raucher, aktueller Status unbekannt",
				"unknown": "Unbekannt"
			}
		},

		"89247-1": {
			"hintText": [
				"\"LA9622-7\": Voll aktiv, in der Lage, alle Leistungen vor der Erkrankung ohne Einschränkung zu erbringen",
				"\"LA9623-5\": Bei körperlich anstrengender Tätigkeit eingeschränkt, aber gehfähig und in der Lage, leichte oder sitzende Arbeiten zu verrichten, z. B. leichte Hausarbeit, Büroarbeit",
				"\"LA9624-3\": Gehfähig und in der Lage, sich selbst zu versorgen, aber nicht in der Lage, Arbeitstätigkeiten zu verrichten. Mehr als 50 % der wachen Zeit auf den Beinen",
				"\"LA9625-0\": Nur begrenzt in der Lage, sich selbst zu versorgen, mehr als 50 % der wachen Zeit an das Bett oder den Stuhl gefesselt",
				"\"LA9626-8\": Völlig behindert. Kann sich nicht mehr selbst versorgen. Völlig an das Bett oder den Stuhl gefesselt",
				"\"LA9627-6\": Tot"
			],
			"legendMapping": {
				"LA9622-7": "Voll aktiv",
				"LA9623-5": "eingeschränkt",
				"LA9624-3": "gehfähig",
				"LA9625-0": "begrenzt",
				"LA9626-8": "völlig behindert",
				"LA9627-6": "Tot"
			}
		},
		"therapy_of_tumor": {
			"hintText": [
				"Bei Patienten mit mehreren onkologischen Diagnosen werden auch Einträge angezeigt, die ggfs. nicht den ausgewählten Suchkriterien entsprechen."
			],
			"aggregations": ["medicationStatements"],
			"tooltips": {
				"OP": "Operationen",
				"ST": "Strahlentherapien",
				"medicationStatements": "Systemische Therapien"
			}
		},
		"medicationStatements": {
			"hintText": [
				"Art der systemischen oder abwartenden Therapie (ADT Basisdatensatz Versionen 2014, 2021)"
			],
			"tooltips": {
				"CH": "Chemotherapie",
				"HO": "Hormontherapie",
				"IM": "Immun-/Antikörpertherapie",
				"KM": "Knochenmarktransplantation",
				"ZS": "zielgerichtete Substanzen",
				"CI": "Chemo- + Immun-/Antikörpertherapie",
				"CZ": "Chemotherapie + zielgerichtete Substanzen",
				"CIZ": "Chemo- + Immun-/Antikörpertherapie + zielgerichtete Substanzen",
				"IZ": "Immun-/Antikörpertherapie + zielgerichtete Substanzen",
				"SZ": "Stammzelltransplantation (inklusive Knochenmarktransplantation)",
				"AS": "Active Surveillance",
				"WS": "Wait and see",
				"WW": "Watchful Waiting",
				"SO": "Sonstiges"
			}
		},
		"sample_kind": {
			"hintText": [
				"Verteilung der Probentypen die mit den identifizierten Patienten verbunden sind."
			],
			"accumulatedValues": [
				{
					"name": "ffpe-tissue",
					"values": [
						"tissue-ffpe",
						"tumor-tissue-ffpe",
						"normal-tissue-ffpe",
						"other-tissue-ffpe"
					]
				},
				{
					"name": "frozen-tissue",
					"values": [
						"tissue-frozen",
						"tumor-tissue-frozen",
						"normal-tissue-frozen",
						"other-tissue-frozen"
					]
				}
			],
			"tooltips": {
				"ffpe-tissue": "Gewebe FFPE",
				"frozen-tissue": "Gewebe schockgefroren",
				"tissue-other": "Gewebe, Andere Konservierungsart",
				"whole-blood": "Vollblut",
				"blood-serum": "Serum",
				"blood-plasma": "Plasma",
				"buffy-coat": "Buffy Coat",
				"peripheral-blood-cells": "Periphere mononukleäre Blutzellen (PBMC)",
				"dried-whole-blood": "Blutkarten",
				"swab": "Abstrich",
				"ascites": "Aszites",
				"stool-faeces": "Stuhl",
				"urine": "Urin",
				"csf-liquor": "Liquor",
				"bone-marrow": "Knochenmark",
				"saliva": "Speichel",
				"liquid-other": "Flüssigprobe, Andere",
				"dna": "DNA",
				"rna": "RNA",
				"derivative-other": "Derivat, Andere"
			},
			"legendMapping": {
				"ffpe-tissue": "Gewebe FFPE",
				"frozen-tissue": "Gewebe schockgefroren",
				"tissue-other": "Gewebe, Andere Konservierungsart",
				"whole-blood": "Vollblut",
				"blood-serum": "Serum",
				"blood-plasma": "Plasma",
				"buffy-coat": "Buffy Coat",
				"peripheral-blood-cells": "Periphere mononukleäre Blutzellen (PBMC)",
				"dried-whole-blood": "Blutkarten",
				"swab": "Abstrich",
				"ascites": "Aszites",
				"stool-faeces": "Stuhl",
				"urine": "Urin",
				"csf-liquor": "Liquor",
				"bone-marrow": "Knochenmark",
				"saliva": "Speichel",
				"liquid-other": "Flüssigprobe, Andere",
				"dna": "DNA",
				"rna": "RNA",
				"derivative-other": "Derivat, Andere"
			}
		}
	},
	"tableOptions": {
		"headerData": [
			{
				"title": "Standorte",
				"dataKey": "site"
			},
			{
				"title": "Patienten",
				"dataKey": "patients"
			},
			{
				"title": "Bioproben*",
				"aggregatedDataKeys": [
					{
						"groupCode": "specimen"
					},
					{
						"stratifierCode": "Histologies",
						"stratumCode": "1"
					}
				]
			}
		]
	},
	"resultSummaryOptions": {
		"title": "Ergebnisse",
		"infoButtonText": "Um eine Re-Identifizierung zu erschweren, werden Standortergebnisse modifiziert und auf Zehnerstellen gerundet. Meldet ein Standort keinen Treffer, wird für diesen null angezeigt.",
		"dataTypes": [
			{
				"title": "Standorte",
				"dataKey": "collections"
			},
			{
				"title": "Patienten",
				"dataKey": "patients"
			}
		]
	}
}

=== samply/nngm-explorer/src/config/options-test.json
{
	"spotUrl": "http://localhost:8055",
	"language": "de",
	"siteMappings": {
        "proxy2": "Proxy2 Test Server",
		"berlin": "Berlin (OBDS)",
		"berlin-test": "Berlin",
		"bonn": "Bonn",
		"dresden": "Dresden",
		"essen": "Essen",
		"frankfurt": "Frankfurt",
		"freiburg": "Freiburg",
		"hannover": "Hannover",
		"mainz": "Mainz",
		"muenchen-lmu": "München(LMU)",
		"muenchen-tum": "München(TUM)",
		"ulm": "Ulm",
		"marburg": "Marburg",
		"luebeck": "UKSH (Lübeck)",
		"wuerzburg": "Würzburg",
		"mannheim": "Mannheim",
		"dktk-test": "DKTK-Test",
		"dktk-datashield-test": "DKTK Datashield Test",
		"hamburg": "Hamburg"
	},
	"chartOptions": {
		"gender": {
			"legendMapping": {
				"male": "Männlich",
				"female": "Weiblich",
				"unknown": "Unbekannt",
				"other": "Divers"
			}
		},
		"diagnosis": {
			"hintText": [
				"Bei Patienten mit mehreren onkologischen Diagnosen werden auch Einträge angezeigt, die ggfs. nicht den ausgewählten Suchkriterien entsprechen."
			]
		},
		"age_at_diagnosis": {
			"hintText": [
				"Bei Patienten mit mehreren Erstdiagnosen werden auch Einträge angezeigt, die ggfs. außerhalb der Suchkriterien liegen. "
			]
		},
		"75186-7": {
			"hintText": [
				"\"verstorben\": ein Todesdatum ist dokumentiert oder das aktuelle Lebensalter ist größer 123 Jahre.",
				"\"lebend\": wird angenommen, wenn kein Todesdatum dokumentiert ist oder das aktuelle Lebensalter nicht 123 Jahre überschritten hat.",
				"\"unbekannt\": kein Geburtsdatum oder Todesdatum bekannt."
			]
		},
		"therapy_of_tumor": {
			"hintText": [
				"Bei Patienten mit mehreren onkologischen Diagnosen werden auch Einträge angezeigt, die ggfs. nicht den ausgewählten Suchkriterien entsprechen."
			],
			"aggregations": ["medicationStatements"],
			"tooltips": {
				"OP": "Operationen",
				"ST": "Strahlentherapien",
				"medicationStatements": "Systemische Therapien"
			}
		},
		"medicationStatements": {
			"hintText": [
				"Art der systemischen oder abwartenden Therapie (ADT Basisdatensatz Versionen 2014, 2021)"
			],
			"tooltips": {
				"CH": "Chemotherapie",
				"HO": "Hormontherapie",
				"IM": "Immun-/Antikörpertherapie",
				"KM": "Knochenmarktransplantation",
				"ZS": "zielgerichtete Substanzen",
				"CI": "Chemo- + Immun-/Antikörpertherapie",
				"CZ": "Chemotherapie + zielgerichtete Substanzen",
				"CIZ": "Chemo- + Immun-/Antikörpertherapie + zielgerichtete Substanzen",
				"IZ": "Immun-/Antikörpertherapie + zielgerichtete Substanzen",
				"SZ": "Stammzelltransplantation (inklusive Knochenmarktransplantation)",
				"AS": "Active Surveillance",
				"WS": "Wait and see",
				"WW": "Watchful Waiting",
				"SO": "Sonstiges"
			}
		},
		"sample_kind": {
			"hintText": [
				"Verteilung der Probentypen die mit den identifizierten Patienten verbunden sind."
			],
			"accumulatedValues": [
				{
					"name": "ffpe-tissue",
					"values": [
						"tissue-ffpe",
						"tumor-tissue-ffpe",
						"normal-tissue-ffpe",
						"other-tissue-ffpe"
					]
				},
				{
					"name": "frozen-tissue",
					"values": [
						"tissue-frozen",
						"tumor-tissue-frozen",
						"normal-tissue-frozen",
						"other-tissue-frozen"
					]
				}
			],
			"tooltips": {
				"ffpe-tissue": "Gewebe FFPE",
				"frozen-tissue": "Gewebe schockgefroren",
				"tissue-other": "Gewebe, Andere Konservierungsart",
				"whole-blood": "Vollblut",
				"blood-serum": "Serum",
				"blood-plasma": "Plasma",
				"buffy-coat": "Buffy Coat",
				"peripheral-blood-cells": "Periphere mononukleäre Blutzellen (PBMC)",
				"dried-whole-blood": "Blutkarten",
				"swab": "Abstrich",
				"ascites": "Aszites",
				"stool-faeces": "Stuhl",
				"urine": "Urin",
				"csf-liquor": "Liquor",
				"bone-marrow": "Knochenmark",
				"saliva": "Speichel",
				"liquid-other": "Flüssigprobe, Andere",
				"dna": "DNA",
				"rna": "RNA",
				"derivative-other": "Derivat, Andere"
			},
			"legendMapping": {
				"ffpe-tissue": "Gewebe FFPE",
				"frozen-tissue": "Gewebe schockgefroren",
				"tissue-other": "Gewebe, Andere Konservierungsart",
				"whole-blood": "Vollblut",
				"blood-serum": "Serum",
				"blood-plasma": "Plasma",
				"buffy-coat": "Buffy Coat",
				"peripheral-blood-cells": "Periphere mononukleäre Blutzellen (PBMC)",
				"dried-whole-blood": "Blutkarten",
				"swab": "Abstrich",
				"ascites": "Aszites",
				"stool-faeces": "Stuhl",
				"urine": "Urin",
				"csf-liquor": "Liquor",
				"bone-marrow": "Knochenmark",
				"saliva": "Speichel",
				"liquid-other": "Flüssigprobe, Andere",
				"dna": "DNA",
				"rna": "RNA",
				"derivative-other": "Derivat, Andere"
			}
		}
	},
	"tableOptions": {
		"headerData": [
			{
				"title": "Standorte",
				"dataKey": "site"
			},
			{
				"title": "Patienten",
				"dataKey": "patients"
			},
			{
				"title": "Bioproben*",
				"dataKey": "specimen"
			}
		]
	},
	"resultSummaryOptions": {
		"title": "Ergebnisse",
		"infoButtonText": "Umfang und Vollständigkeit der abfragbaren Daten hängt vom Datenimport in die lokalen Brückenköpfe durch die Standorte ab. Bekannte Limitation sind unter \"Known Issues\" (siehe „Weiterführende Informationen“) aufgeführt. Um eine Re-Identifizierung zu erschweren, werden Standortergebnisse modifiziert und auf Zehnerstellen gerundet. Meldet ein Standort keinen Treffer, wird für diesen null angezeigt.",
		"dataTypes": [
			{
				"title": "Standorte",
				"dataKey": "collections"
			},
			{
				"title": "Patienten",
				"dataKey": "patients"
			},
			{
				"title": "Bioproben",
				"dataKey": "specimen"
			}
		]
	},
	"projectmanagerOptions": {
		"newProjectUrl": "https://requests.dktk.dkfz.de/project-manager-api/create-query-and-design-project",
		"editProjectUrl": "https://requests.dktk.dkfz.de/project-manager-api/edit-project",
		"siteMappings": [
			{
				"site": "DKTK-Test",
				"collection": "lens-dktk-test"
			},
			{
				"site": "dktk-datashield-test",
				"collection": "lens-dktk-datashield-test"
			},
			{
				"site": "Berlin",
				"collection": "lens-berlin"
			},
			{
				"site": "Berlin (OBDS)",
				"collection": "lens-berlin"
			},
			{
				"site": "Dresden",
				"collection": "lens-dresden"
			},
			{
				"site": "Essen",
				"collection": "lens-essen"
			},
			{
				"site": "Frankfurt",
				"collection": "lens-frankfurt"
			},
			{
				"site": "Freiburg",
				"collection": "lens-freiburg"
			},
			{
				"site": "Hannover",
				"collection": "lens-hannover"
			},
			{
				"site": "Mainz",
				"collection": "lens-mainz"
			},
			{
				"site": "München(LMU)",
				"collection": "lens-muenchen-lmu"
			},
			{
				"site": "München(TUM)",
				"collection": "lens-muenchen-tum"
			},
			{
				"site": "Ulm",
				"collection": "lens-ulm"
			},
			{
				"site": "Würzburg",
				"collection": "lens-wuerzburg"
			},
			{
				"site": "Mannheim",
				"collection": "lens-mannheim"
			},
			{
				"site": "Hamburg",
				"collection": "lens-hamburg"
			}
		]
	}
}
